from collections import defaultdict, deque
import re


def tokenize(text):
    return set(re.findall(r"[a-zA-Z]+", text.lower()))


def method_class(method_name):
    return method_name.split(".")[0]


def print_set(title, items):
    print(title)
    for item in sorted(items):
        print(f"  - {item}")
    print()


def evolutionary_coupling(seed, commit_history):
    """
    Simplified evolutionary coupling:
    Find previous commits where the file/class containing the seed method was modified,
    then collect all methods co-changed in those commits.
    """
    seed_cls = method_class(seed)
    history_based_set = {seed}
    used_commits = []

    for commit in commit_history:
        modified_methods = set(commit["modified_methods"])
        contains_seed_file = any(method_class(m) == seed_cls for m in modified_methods)

        if contains_seed_file:
            history_based_set.update(modified_methods)
            used_commits.append(commit["id"])

    return history_based_set, used_commits


def expand_dependence(history_set, dependence_graph, class_members, hop_limit=1):
    """
    Simplified dependence coupling:
    Add direct/indirect call dependencies and class-member dependencies.
    """
    expanded = set(history_set)

    for method in list(history_set):
        # direct / indirect call dependencies
        queue = deque([(method, 0)])
        visited = {method}

        while queue:
            current, depth = queue.popleft()

            if depth >= hop_limit:
                continue

            for neighbor in dependence_graph.get(current, []):
                expanded.add(neighbor)

                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append((neighbor, depth + 1))

        # class-member dependencies
        cls = method_class(method)
        for member in class_members.get(cls, []):
            expanded.add(member)

    return expanded


def build_undirected_edges(candidate_set, dependence_graph, class_members):
    edges = defaultdict(set)

    # call edges
    for src, targets in dependence_graph.items():
        if src in candidate_set:
            for dst in targets:
                if dst in candidate_set:
                    edges[src].add(dst)
                    edges[dst].add(src)

    # class-member edges
    for cls, members in class_members.items():
        members_in_candidate = [m for m in members if m in candidate_set]

        for i in range(len(members_in_candidate)):
            for j in range(i + 1, len(members_in_candidate)):
                a = members_in_candidate[i]
                b = members_in_candidate[j]
                edges[a].add(b)
                edges[b].add(a)

    for method in candidate_set:
        edges[method]  # ensure isolated nodes exist

    return edges


def connected_components(candidate_set, dependence_graph, class_members):
    edges = build_undirected_edges(candidate_set, dependence_graph, class_members)
    visited = set()
    clusters = []

    for method in candidate_set:
        if method in visited:
            continue

        cluster = set()
        stack = [method]
        visited.add(method)

        while stack:
            current = stack.pop()
            cluster.add(current)

            for neighbor in edges[current]:
                if neighbor not in visited:
                    visited.add(neighbor)
                    stack.append(neighbor)

        clusters.append(cluster)

    return clusters


def simplified_planner(change_intent, seed):
    """
    Simplified Planner:
    In the original Ripple, this is generated by an LLM.
    Here, we generate a small rule-based change plan.
    """
    plan = [
        f"Start from the seed method {seed}.",
        "Check methods related to dependency conflict computation.",
        "Inspect eviction-related methods because the intent mentions eviction behavior.",
        "Update methods that may participate in dependency resolution consistency.",
        "Include test methods that validate the eviction conflict scenario."
    ]

    return plan


def simplified_reasoner(cluster, change_intent, plan, method_summaries, history_set, seed, sample_id):
    """
    Simplified Reasoner:
    In the original Ripple, this is performed by an LLM with self-consistency.
    Here, we simulate multiple predictions using slightly different thresholds.
    """
    intent_tokens = tokenize(change_intent + " " + " ".join(plan))
    prediction = set()

    # Different thresholds simulate multiple reasoning samples.
    thresholds = {
        1: 2,
        2: 3,
        3: 2
    }

    threshold = thresholds.get(sample_id, 2)

    for method in cluster:
        if method == seed:
            continue

        method_text = method + " " + method_summaries.get(method, "")
        method_tokens = tokenize(method_text)

        keyword_overlap = len(intent_tokens & method_tokens)

        score = keyword_overlap

        if method in history_set:
            score += 1

        if "Test" in method or "test" in method:
            score += 1

        # Slight variation across samples
        if sample_id == 2 and "eviction" in method_text.lower():
            score += 1

        if sample_id == 3 and "dependency" in method_text.lower():
            score += 1

        if score >= threshold:
            prediction.add(method)

    return prediction


def precision_recall_f1(predicted, actual):
    if not predicted:
        precision = 0.0
    else:
        precision = len(predicted & actual) / len(predicted)

    if not actual:
        recall = 0.0
    else:
        recall = len(predicted & actual) / len(actual)

    if precision + recall == 0:
        f1 = 0.0
    else:
        f1 = 2 * precision * recall / (precision + recall)

    return precision, recall, f1


def run_simplified_ripple():
    # -----------------------------
    # 1. Small example input
    # -----------------------------
    seed = "ResolveEngine.computeConflicts"

    change_intent = (
        "Fix an eviction-related dependency conflict resolution problem. "
        "The resolver should handle evicted modules safely and avoid inconsistent "
        "dependency resolution results."
    )

    commit_history = [
        {
            "id": "c001",
            "modified_methods": [
                "ResolveEngine.computeConflicts",
                "IvyNodeEviction.markEvicted",
                "IvyNode.isEvicted",
                "ResolveTest.testEvictionConflict"
            ]
        },
        {
            "id": "c002",
            "modified_methods": [
                "ResolveEngine.resolveConflict",
                "IvyNodeEviction.getEvictedNodes",
                "IvyNode.isEvicted"
            ]
        },
        {
            "id": "c003",
            "modified_methods": [
                "Parser.parseConfig",
                "Parser.validateInput"
            ]
        }
    ]

    dependence_graph = {
        "ResolveEngine.computeConflicts": [
            "ResolveEngine.resolveConflict",
            "IvyNodeEviction.markEvicted"
        ],
        "ResolveEngine.resolveConflict": [
            "IvyNode.isEvicted",
            "IvyNodeEviction.getEvictedNodes"
        ],
        "IvyNodeEviction.markEvicted": [
            "IvyNode.isEvicted"
        ],
        "ResolveTest.testEvictionConflict": [
            "ResolveEngine.computeConflicts"
        ],
        "Parser.parseConfig": [
            "Parser.validateInput"
        ]
    }

    class_members = {
        "ResolveEngine": [
            "ResolveEngine.computeConflicts",
            "ResolveEngine.resolveConflict",
            "ResolveEngine.getDependencies"
        ],
        "IvyNodeEviction": [
            "IvyNodeEviction.markEvicted",
            "IvyNodeEviction.getEvictedNodes"
        ],
        "IvyNode": [
            "IvyNode.isEvicted",
            "IvyNode.getDependencyDescriptor"
        ],
        "ResolveTest": [
            "ResolveTest.testEvictionConflict",
            "ResolveTest.testNormalResolve"
        ],
        "Parser": [
            "Parser.parseConfig",
            "Parser.validateInput"
        ]
    }

    method_summaries = {
        "ResolveEngine.computeConflicts":
            "Computes dependency conflicts during the resolution process.",
        "ResolveEngine.resolveConflict":
            "Resolves conflicts among dependency candidates.",
        "ResolveEngine.getDependencies":
            "Retrieves dependencies used during resolve.",
        "IvyNodeEviction.markEvicted":
            "Marks a dependency node as evicted and handles eviction state.",
        "IvyNodeEviction.getEvictedNodes":
            "Returns dependency nodes that were evicted during resolution.",
        "IvyNode.isEvicted":
            "Checks whether a dependency node has been evicted.",
        "IvyNode.getDependencyDescriptor":
            "Returns descriptor information for a dependency node.",
        "ResolveTest.testEvictionConflict":
            "Tests dependency conflict resolution when eviction occurs.",
        "ResolveTest.testNormalResolve":
            "Tests normal dependency resolution behavior.",
        "Parser.parseConfig":
            "Parses configuration files.",
        "Parser.validateInput":
            "Validates parser input."
    }

    # This is only for demonstration/evaluation in the assignment screenshot.
    ground_truth = {
        "ResolveEngine.resolveConflict",
        "IvyNodeEviction.markEvicted",
        "IvyNodeEviction.getEvictedNodes",
        "IvyNode.isEvicted",
        "ResolveTest.testEvictionConflict"
    }

    # -----------------------------
    # 2. Run simplified Ripple
    # -----------------------------
    print("=" * 70)
    print("Simplified Ripple Prototype")
    print("=" * 70)
    print(f"Seed edit location: {seed}")
    print(f"Change intent: {change_intent}")
    print()

    print("[Step 1] Initial impact set")
    initial_set = {seed}
    print_set("I0:", initial_set)

    print("[Step 2] Evolutionary coupling-based expansion")
    history_set, used_commits = evolutionary_coupling(seed, commit_history)
    print(f"Relevant commits used: {used_commits}")
    print_set("History-based impact set IH:", history_set)

    print("[Step 3] Dependence coupling-based expansion")
    dependence_set = expand_dependence(
        history_set,
        dependence_graph,
        class_members,
        hop_limit=1
    )
    print_set("Dependence-enhanced impact set ID:", dependence_set)

    print("[Step 4] Dependence clustering")
    clusters = connected_components(dependence_set, dependence_graph, class_members)

    for idx, cluster in enumerate(clusters, start=1):
        print_set(f"Cluster D{idx}:", cluster)

    print("[Step 5] Simplified change plan generation")
    plan = simplified_planner(change_intent, seed)

    for idx, step in enumerate(plan, start=1):
        print(f"  P{idx}. {step}")
    print()

    print("[Step 6] Cluster-level impact prediction with self-consistency")
    final_impact_set = set()
    K = 3

    for idx, cluster in enumerate(clusters, start=1):
        sample_predictions = []

        print(f"Cluster D{idx} predictions:")

        for sample_id in range(1, K + 1):
            prediction = simplified_reasoner(
                cluster=cluster,
                change_intent=change_intent,
                plan=plan,
                method_summaries=method_summaries,
                history_set=history_set,
                seed=seed,
                sample_id=sample_id
            )

            sample_predictions.append(prediction)
            print(f"  Sample {sample_id}: {sorted(prediction)}")

        if sample_predictions:
            refined_prediction = set.intersection(*sample_predictions)
        else:
            refined_prediction = set()

        print(f"  Refined cluster impact subset I{idx}: {sorted(refined_prediction)}")
        print()

        final_impact_set.update(refined_prediction)

    print("[Step 7] Final impact set aggregation")
    print_set("Final impact set If:", final_impact_set)

    print("[Optional] Simple evaluation on manually constructed ground truth")
    print_set("Ground-truth impact set:", ground_truth)

    precision, recall, f1 = precision_recall_f1(final_impact_set, ground_truth)

    print(f"Precision: {precision:.2f}")
    print(f"Recall:    {recall:.2f}")
    print(f"F1-score:  {f1:.2f}")
    print()
    print("Note: This is a simplified educational prototype.")
    print("The Planner and Reasoner are heuristic approximations of the LLM components in Ripple.")


if __name__ == "__main__":
    run_simplified_ripple()
    